version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ${pwd}/db-data/:/var/lib/postgresql/data/
      - ${pwd}/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
    
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge